[package]
name = "investing-api"
version = "0.2.2"
edition = "2021"
authors = ["github.com/jerryshell/investing-api"]

[dependencies]
reqwest = { version = "0.11.10", default-features = false, features = [
    "rustls-tls",
] }
tokio = { version = "1.18.2", features = ["full"] }
tokio-test = "0.4.2"
serde = "1.0.137"
serde_json = "1.0.81"
serde_derive = "1.0.137"
futures = "0.3.21"
csv = "1.1.6"
clap = { version = "3.1.18", features = ["derive"] }
anyhow = "1.0.57"
scraper = "0.13.0"
chrono = "0.4.19"

[profile.release]
lto = true
